/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jxK7rhwUCP2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Accordion, AccordionItem, AccordionTrigger, AccordionChevron, AccordionContent } from "@/components/ui/accordion"

export function Component() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Name</TableHead>
          <TableHead>Email</TableHead>
          <TableHead>Phone</TableHead>
          <TableHead className="w-[50px]" />
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell>
            <Accordion type="single" collapsible>
              <AccordionItem value="user-1">
                <AccordionTrigger className="flex items-center gap-2">
                  <span>John Doe</span>
                  <div className="ml-auto" />
                </AccordionTrigger>
                <AccordionContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Address</TableHead>
                        <TableHead>City</TableHead>
                        <TableHead>State</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>123 Main St</TableCell>
                        <TableCell>Anytown</TableCell>
                        <TableCell>CA</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </TableCell>
          <TableCell>john@example.com</TableCell>
          <TableCell>(555) 555-5555</TableCell>
          <TableCell />
        </TableRow>
        <TableRow>
          <TableCell>
            <Accordion type="single" collapsible>
              <AccordionItem value="user-2">
                <AccordionTrigger className="flex items-center gap-2">
                  <span>Jane Smith</span>
                  <div className="ml-auto" />
                </AccordionTrigger>
                <AccordionContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Address</TableHead>
                        <TableHead>City</TableHead>
                        <TableHead>State</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>456 Oak Rd</TableCell>
                        <TableCell>Somewhere</TableCell>
                        <TableCell>NY</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </TableCell>
          <TableCell>jane@example.com</TableCell>
          <TableCell>(555) 555-5556</TableCell>
          <TableCell />
        </TableRow>
        <TableRow>
          <TableCell>
            <Accordion type="single" collapsible>
              <AccordionItem value="user-3">
                <AccordionTrigger className="flex items-center gap-2">
                  <span>Bob Johnson</span>
                  <div className="ml-auto" />
                </AccordionTrigger>
                <AccordionContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Address</TableHead>
                        <TableHead>City</TableHead>
                        <TableHead>State</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>789 Elm St</TableCell>
                        <TableCell>Somewhere Else</TableCell>
                        <TableCell>TX</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </TableCell>
          <TableCell>bob@example.com</TableCell>
          <TableCell>(555) 555-5557</TableCell>
          <TableCell />
        </TableRow>
      </TableBody>
    </Table>
  )
}
